name        : sratom
version     : 0.4.6
release     : 1
source      :
    - http://download.drobilla.net/sratom-0.4.6.tar.bz2 : a4b9beaeaedc4f651beb15cd1cfedff905b0726a9010548483475ad97d941220
license     : ISC
component   : programming
summary     : A library for serialising LV2 atoms to or from RDF
description : A library for serialising LV2 atoms to or from RDF, particularly the Turtle syntax.
builddeps   :
    - pkgconfig(lv2)
    - pkgconfig(serd-0)
    - pkgconfig(sord-0)
setup       : |
    ./waf configure --prefix=%PREFIX% --libdir=%libdir%
build       : |
    ./waf build
install     : |
    ./waf install --destdir="$installdir"
