name       : sratom
version    : 0.6.4
release    : 4
source     :
    - git|https://github.com/lv2/sratom.git : v0.6.4
license    : ISC
component  : programming.library
summary    : A library for serialising LV2 atoms to or from RDF
description: A library for serialising LV2 atoms to or from RDF, particularly the Turtle syntax.
builddeps  :
    - pkgconfig(lv2)
    - pkgconfig(serd-0)
    - pkgconfig(sord-0)
setup      : |
    %waf_configure --libdir=%libdir%
build      : |
    %waf_build
install    : |
    %waf_install
