name       : sratom
version    : 0.6.0
release    : 2
source     :
    - http://download.drobilla.net/sratom-0.6.0.tar.bz2 : 440ac2b1f4f0b7878f8b95698faa1e8f8c50929a498f68ec5d066863626a3d43
license    : ISC
component  : programming
summary    : A library for serialising LV2 atoms to or from RDF
description: A library for serialising LV2 atoms to or from RDF, particularly the Turtle syntax.
builddeps  :
    - pkgconfig(lv2)
    - pkgconfig(serd-0)
    - pkgconfig(sord-0)
setup      : |
    %waf_configure --libdir=%libdir%
build      : |
    %waf_build
install    : |
    %waf_install
