name        : sratom
version     : 0.4.6
release     : 1
source      :
    - http://download.drobilla.net/sratom-0.4.6.tar.bz2 : a4b9beaeaedc4f651beb15cd1cfedff905b0726a9010548483475ad97d941220
license     :
    - ISC
component   : programming.devel
summary     : A library for serialising LV2 atoms to or from RDF
builddeps   :
    - lv2-devel
    - serd-devel
    - sord-devel
description : A library for serialising LV2 atoms to or from RDF, particularly the Turtle syntax.
setup       : |
    %workdir%/waf configure --prefix=%PREFIX% --libdir=%libdir%
build       : |
    %workdir%/waf build
install     : |
    %workdir%/waf install --destdir="$installdir"
