name       : sratom
version    : 0.6.2
release    : 3
source     :
    - https://github.com/drobilla/sratom/archive/v0.6.2.tar.gz : de4adc09a767a991cb6851fd167ab78199fbc9ebbe6ab7dc86eea148524114ef
license    : ISC
component  : programming.library
summary    : A library for serialising LV2 atoms to or from RDF
description: A library for serialising LV2 atoms to or from RDF, particularly the Turtle syntax.
builddeps  :
    - pkgconfig(lv2)
    - pkgconfig(serd-0)
    - pkgconfig(sord-0)
setup      : |
    %waf_configure --libdir=%libdir%
build      : |
    %waf_build
install    : |
    %waf_install
